"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var Shape_1 = require("./Shape");
var myShape = new Shape_1.Shape(1, 1);
console.log(myShape.getInfo());
var myCircle = new Circle_1.Circle(2, 2, 20);
console.log(myCircle.getInfo());
var myRectangle = new Rectangle_1.Rectangle(3, 3, 30, 30);
console.log(myRectangle.getInfo());
